name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Generates the snake  
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: SivuyileMtwetwe  # Your exact GitHub username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Push the changes
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generate Snake Animation'
          add: 'dist'
          push: true
          branch: main

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output