name: Generate Snake Contribution Animation

on:
  # Run workflow every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Allows you to run the workflow manually
  workflow_dispatch:
  # Run workflow when there's a push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: SivuyileMtwetwe  # replace with your GitHub username
          output: dist/github-contribution-grid-snake.svg

      - name: Upload the SVG
        uses: actions/upload-artifact@v2
        with:
          name: snake_animation
          path: dist/github-contribution-grid-snake.svg
